export const Users = [
    {
        id:1,
        profilePicture: "assets/person/1.jpg",
        username: "Vinal Basileios",
        liveIn: "Austin",
        cookingExperience: "2 years",
        favFood: "French Toast",
        favRecipePicture: "assets/food/appleSauce.png",
        favRecipeName: "Ginger Bread",
    },
    {
        id:2,
        profilePicture: "assets/person/2.jpg",
        username: "Farai Siegbert",
        liveIn: "Frankfurt",
        cookingExperience: "5 years",
        favFood: "Bagel",
        favRecipePicture: "assets/food/cookies.png",
        favRecipeName: "Cookies",
    },
    {
        id:3,
        profilePicture: "assets/person/3.jpg",
        username: "Jonna Olujimi",
        liveIn: "Marseille",
        cookingExperience: "never",
        favFood: "Ribs",
        favRecipePicture: "assets/food/salad.png",
        favRecipeName: "Salad",
    },
    {
        id:4,
        profilePicture: "assets/person/4.jpg",
        username: "Ephrath Augustine",
        liveIn: "LA",
        cookingExperience: "1 year",
        favFood: "Popcorn",
        favRecipePicture: "assets/food/ham.png",
        favRecipeName: "Ham",
    },
    {
        id:5,
        profilePicture: "assets/person/5.jpg",
        username: "Estelle Carlitos",
        liveIn: "Havana",
        cookingExperience: "4 years",
        favFood: "Croissant",
        favRecipePicture: "assets/food/appleSauce.png",
        favRecipeName: "Apple Sauce",
    },
    {
        id:6,
        profilePicture: "assets/person/6.jpg",
        username: "LaShawn Beau",
        liveIn: "Dubai",
        cookingExperience: "3 months",
        favFood: "Muffins",
        favRecipePicture: "assets/food/donuts.png",
        favRecipeName: "Donuts",
    },
    {
        id:7,
        profilePicture: "assets/person/7.jpg",
        username: "Omari Paulette",
        liveIn: "Kuwait City",
        cookingExperience: "1 month",
        favFood: "Donuts",
        favRecipePicture: "assets/food/lambChops.png",
        favRecipeName: "Lamb Chops",
    },
    {
        id:8,
        profilePicture: "assets/person/8.jpg",
        username: "Brock Caroline",
        liveIn: "Thimphu",
        cookingExperience: "10 years",
        favFood: "Crepes",
        favRecipePicture: "assets/food/sushi.png",
        favRecipeName: "Sushi",
    },
    {
        id:9,
        profilePicture: "assets/person/9.jpg",
        username: "Hannes Konrad",
        liveIn: "Glasgow",
        cookingExperience: "30 years",
        favFood: "Mashed Potatoes",
        favRecipePicture: "assets/food/brownies.png",
        favRecipeName: "Brownies",
    },
    {
        id:10,
        profilePicture: "assets/person/10.jpg",
        username: "Nikhil Mijav",
        liveIn: "Minsk",
        cookingExperience: "10 days",
        favFood: "Ice Cream Cake",
        favRecipePicture: "assets/food/steak.png",
        favRecipeName: "Steak",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Best food ever",
        photo: "assets/post/1.jpg",
        date: "5 mins ago",
        userID: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assets/post/2.jpg",
        date: "15 mins ago",
        userID: 2,
        like: 12,
        comment: 3,
    },
    {
        id: 3,
        desc: "It was hard",
        photo: "assets/post/3.jpg",
        date: "50 mins ago",
        userID: 3,
        like: 15,
        comment: 2,
    },
    {
        id: 4,
        photo: "assets/post/4.jpg",
        date: "1 hour ago",
        userID: 4,
        like: 500,
        comment: 100,
    },
    {
        id: 5,
        photo: "assets/post/5.jpg",
        date: "5 hours ago",
        userID: 5,
        like: 84,
        comment: 34,
    },
    {
        id: 6,
        desc: "Looks good!",
        photo: "assets/post/6.jpg",
        date: "2 days ago",
        userID: 6,
        like: 2,
        comment: 0,
    },
    {
        id: 7,
        desc: "Looks good!",
        photo: "assets/post/6.jpg",
        date: "2 days ago",
        userID: 7,
        like: 2,
        comment: 0,
    },
    {
        id: 8,
        desc: "Looks good!",
        photo: "assets/post/6.jpg",
        date: "2 days ago",
        userID: 8,
        like: 2,
        comment: 0,
    },
    {
        id: 9,
        desc: "Looks good!",
        photo: "assets/post/6.jpg",
        date: "2 days ago",
        userID: 9,
        like: 2,
        comment: 0,
    },
    {
        id: 10,
        desc: "Looks good!",
        photo: "assets/post/6.jpg",
        date: "2 days ago",
        userID: 10,
        like: 2,
        comment: 0,
    },
];
